### ISSUE TITLE
Left border of grouped buttons missing

### ISSUE THREAD

**Issue by rcastill** [monday15/lounge-gtk-theme#18]
Here is an example of 2 buttons grouped together. The left one is missing its side border (as opposed to the single button):

![image](https://user-images.githubusercontent.com/8534987/90803580-f771b080-e2e6-11ea-8246-9bbb870a8d22.png)

I found the same in selects:
![image](https://user-images.githubusercontent.com/8534987/90803686-20924100-e2e7-11ea-9c43-a5c7a3726421.png)

Best theme BTW

**Comment by ptrxyz** [comment]
Can confirm, found the same issue. Compiled this for GTK3.24.

**Comment by ptrxyz** [comment]
Add this to the end of `.themes/Lounge-night/gtk.css` (and the other versions if it is relevant to you) as a workaround:

```css
.linked > button:not(entry):first-child {
    border-left-color: rgb(37, 37, 37);
}
```

**Comment by pztrn** [comment]
This workaround isn't conform to other border's color. Use this instead:

```css
.linked > button:not(entry):first-child {
    border-left-color: rgba(32, 32, 32, 0.3);
}
```
